export const STATES = {
  S0_SITE_ARRIVAL: 'S0',
  S1_DARKNESS: 'S1',
  S2_DISTANT_SPECK: 'S2',
  S3_LOGO_MANIFESTATION: 'S3',
  S4_LIVING_WEAVE: 'S4',
  S5_PORTAL_ENTRY: 'S5',
  S6_WEAVE_PASSAGE: 'S6',
  S7_EARTH_REVEAL: 'S7',
  S8_READING_ROOM_INVITATION: 'S8',
  S9_READING_ROOM_INIT: 'S9',
  S10_OPENING_ARC_READING: 'S10',
  S11_SHARE_OPPORTUNITY: 'S11',
  S12_CONTINUE_READING: 'S12',
  S13_OPENING_ARC_COMPLETE: 'S13',
  S14_CHOOSE_YOUR_PATH: 'S14',
};

export const STATE_ORDER = Object.freeze([
  STATES.S0_SITE_ARRIVAL,
  STATES.S1_DARKNESS,
  STATES.S2_DISTANT_SPECK,
  STATES.S3_LOGO_MANIFESTATION,
  STATES.S4_LIVING_WEAVE,
  STATES.S5_PORTAL_ENTRY,
  STATES.S6_WEAVE_PASSAGE,
  STATES.S7_EARTH_REVEAL,
  STATES.S8_READING_ROOM_INVITATION,
  STATES.S9_READING_ROOM_INIT,
  STATES.S10_OPENING_ARC_READING,
  STATES.S11_SHARE_OPPORTUNITY,
  STATES.S12_CONTINUE_READING,
  STATES.S13_OPENING_ARC_COMPLETE,
  STATES.S14_CHOOSE_YOUR_PATH,
]);

export const CINEMATIC_STATES = Object.freeze([
  STATES.S1_DARKNESS,
  STATES.S2_DISTANT_SPECK,
  STATES.S3_LOGO_MANIFESTATION,
  STATES.S4_LIVING_WEAVE,
  STATES.S5_PORTAL_ENTRY,
  STATES.S6_WEAVE_PASSAGE,
  STATES.S7_EARTH_REVEAL,
]);

export const IMMERSION_STATES = Object.freeze({
  ENTRY: 'entry',
  ORIENTATION: 'orientation',
  READING: 'reading',
  RECOGNITION: 'recognition',
  REFLECTION: 'reflection',
  DECOMPRESSION: 'decompression',
  SHARING_READY: 'sharing_ready',
  RETURN: 'return',
  CONVERGENCE: 'convergence',
  BECOME_FAMILY_THRESHOLD: 'become_family_threshold',
});

export const IMMERSION_ORDER = Object.freeze([
  IMMERSION_STATES.ENTRY,
  IMMERSION_STATES.ORIENTATION,
  IMMERSION_STATES.READING,
  IMMERSION_STATES.RECOGNITION,
  IMMERSION_STATES.REFLECTION,
  IMMERSION_STATES.DECOMPRESSION,
  IMMERSION_STATES.SHARING_READY,
  IMMERSION_STATES.RETURN,
  IMMERSION_STATES.CONVERGENCE,
  IMMERSION_STATES.BECOME_FAMILY_THRESHOLD,
]);

export const PACE_MODES = Object.freeze({
  SLOW: 'slow',
  NATURAL: 'natural',
  DEEP: 'deep',
  PAUSED: 'paused',
  RETURNING: 'returning',
});

export const EVENTS = Object.freeze({
  LANDING_STARTED: 'LandingStarted',
  LOGO_MANIFESTATION_STARTED: 'LogoManifestationStarted',
  PORTAL_ENTRY_STARTED: 'PortalEntryStarted',
  EARTH_REVEAL_COMPLETED: 'EarthRevealCompleted',
  READING_ROOM_ENTERED: 'ReadingRoomEntered',
  READING_SESSION_STARTED: 'ReadingSessionStarted',
  CHAPTER_COMPLETED: 'ChapterCompleted',
  SHARE_PROMPT_DISPLAYED: 'SharePromptDisplayed',
  SHARE_COMPLETED: 'ShareCompleted',
  OPENING_ARC_COMPLETED: 'OpeningArcCompleted',
  PATHWAY_SELECTED: 'PathwaySelected',
  SHARE_TOKEN_OPENED: 'ShareTokenOpened',
});

export const ONCE_PER_SESSION_EVENTS = Object.freeze([
  EVENTS.LANDING_STARTED,
  EVENTS.LOGO_MANIFESTATION_STARTED,
  EVENTS.PORTAL_ENTRY_STARTED,
  EVENTS.EARTH_REVEAL_COMPLETED,
  EVENTS.READING_ROOM_ENTERED,
  EVENTS.READING_SESSION_STARTED,
  EVENTS.OPENING_ARC_COMPLETED,
]);

export const INTENTS = Object.freeze({
  ADVANCE: 'advance',
  SKIP: 'skip',
  CROSS: 'cross',
  BACK: 'back',
  ENTER: 'enter',
  COMPLETE: 'complete',
});

export const READER_INTENTS = Object.freeze([INTENTS.ADVANCE, INTENTS.ENTER, INTENTS.BACK]);

export const MOTION_PREFERENCES = Object.freeze({
  FULL: 'full',
  REDUCED: 'reduced',
  OFF: 'off',
});

export const READING_THEMES = Object.freeze({ DARK: 'dark', LIGHT: 'light' });

export const AGE_BAND_TO_CONTENT_LAYER = Object.freeze({
  '8-12': 'foundation',
  '13-16': 'awakening',
  '17-19': 'transition',
  '20-25': 'emerging_adult',
  '26-32': 'grounded_adult',
  '33+': 'full_manuscript',
});

export const DEFAULT_CONTENT_LAYER = 'full_manuscript';

export const contentLayerForAgeBand = (ageBand) =>
  AGE_BAND_TO_CONTENT_LAYER[ageBand] ?? DEFAULT_CONTENT_LAYER;

export const RESUME_CHECKPOINTS = Object.freeze([
  STATES.S1_DARKNESS,
  STATES.S9_READING_ROOM_INIT,
  STATES.S10_OPENING_ARC_READING,
  STATES.S14_CHOOSE_YOUR_PATH,
]);

export const READING_STATES = Object.freeze([
  STATES.S10_OPENING_ARC_READING,
  STATES.S11_SHARE_OPPORTUNITY,
  STATES.S12_CONTINUE_READING,
  STATES.S13_OPENING_ARC_COMPLETE,
]);

export const stateIndex = (state) => STATE_ORDER.indexOf(state);

export const isCinematic = (state) => CINEMATIC_STATES.includes(state);

export const isReadingState = (state) => READING_STATES.includes(state);
